# Generated by Django 4.2.7 on 2023-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfeeder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='servingsPerDay',
        ),
        migrations.AddField(
            model_name='pet',
            name='servingTime1',
            field=models.CharField(default='none', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='servingTime2',
            field=models.CharField(default='none', max_length=6),
            preserve_default=False,
        ),
    ]
